#!/bin/bash

# # source environment variables for OpenStack and UCD
# source ~/openrc

PATTERN_NAME=jke
DS_USERNAME=admin
DS_PASSWORD=admin
DS_WEB_URL=http://192.168.27.100:8080

# add example jke application to UCD
udclient createVersion -component jke.war -name 4.0
udclient addVersionFiles -component jke.war -version 4.0 -base /jke/jke.war/artifacts/ -exclude .DS_Store

#/jke/init-tutorial

